version: '3'

services:
  app:
    image: docker-nextjs-store-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    # volumes:
    #   - .:/app
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://postgres:password@db:5432/app
